#!/bin/bash

# ============================================================
# KenXploit Auto Installer
# ============================================================
# Universal installer for Linux & macOS
# - Install Python dependencies
# - Register 'kenxploit' command to system PATH
# - Verify installation
# ============================================================

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

KENXPLOIT_DIR="$(cd "$(dirname "$(readlink -f "$0" 2>/dev/null || echo "$0")")" && pwd)"
KENXPLOIT_BIN="$KENXPLOIT_DIR/kenxploit"
BIN_DIR="/usr/local/bin"
WRAPPER="$BIN_DIR/kenxploit"

banner() {
  echo -e "${CYAN}"
  echo "╔══════════════════════════════════════════════╗"
  echo "║         KenXploit Auto Installer             ║"
  echo "║   Ultimate AI Pentesting Framework           ║"
  echo "╚══════════════════════════════════════════════╝"
  echo -e "${NC}"
}

info()    { echo -e "  ${GREEN}[+]${NC} $1"; }
warn()    { echo -e "  ${YELLOW}[!]${NC} $1"; }
error()   { echo -e "  ${RED}[-]${NC} $1"; }
success() { echo -e "  ${GREEN}[✓]${NC} $1"; }
fail()    { echo -e "  ${RED}[x]${NC} $1"; }

check_root() {
  if [ "$EUID" -ne 0 ] && [ "$(uname)" != "Darwin" ]; then
    error "Requires root privileges."
    warn  "Run with: sudo ./install.sh"
    exit 1
  fi
}

detect_python() {
  if command -v python3 &>/dev/null; then
    PYTHON="python3"
  elif command -v python &>/dev/null; then
    PYTHON="python"
  else
    PYTHON=""
  fi
}

detect_shell_rc() {
  SHELL_RC=""
  case "$(basename "$SHELL")" in
    zsh)  SHELL_RC="$HOME/.zshrc" ;;
    bash) SHELL_RC="$HOME/.bashrc" ;;
    *)
      [ -f "$HOME/.zshrc" ]  && SHELL_RC="$HOME/.zshrc"
      [ -f "$HOME/.bashrc" ] && SHELL_RC="$HOME/.bashrc"
      ;;
  esac
}

# ============================================================

banner

# --- Step 1: Check Python ---
info "Checking Python..."
detect_python
if [ -z "$PYTHON" ]; then
  fail "Python not found!"
  echo ""
  echo "  Install Python 3 first:"
  echo "    Debian/Ubuntu:  sudo apt install python3 python3-pip"
  echo "    Arch:           sudo pacman -S python python-pip"
  echo "    macOS:          brew install python3"
  echo "    Fedora:         sudo dnf install python3 python3-pip"
  exit 1
fi
success "Python: $($PYTHON --version 2>&1)"

# --- Step 2: Check binary ---
info "Checking KenXploit binary..."
if [ ! -f "$KENXPLOIT_BIN" ]; then
  fail "Binary not found: $KENXPLOIT_BIN"
  exit 1
fi
chmod +x "$KENXPLOIT_BIN"
success "Binary: $KENXPLOIT_BIN"

# --- Step 3: Install dependencies ---
info "Installing Python dependencies..."
if [ -f "$KENXPLOIT_DIR/requirements.txt" ]; then
  if $PYTHON -m pip install -r "$KENXPLOIT_DIR/requirements.txt" -q 2>/dev/null; then
    success "Dependencies installed"
  else
    warn "pip install failed — install manually:"
    echo "       $PYTHON -m pip install -r requirements.txt"
  fi
else
  warn "No requirements.txt, skipping"
fi

# --- Step 4: Register to PATH ---
info "Registering 'kenxploit' to PATH..."

WRAPPER_SCRIPT="#!/bin/bash
# KenXploit wrapper — generated by install.sh
cd \"$KENXPLOIT_DIR\" && exec \"$KENXPLOIT_DIR/kenxploit\" \"\$@\"
"

REGISTERED=0

# Method 1: Write to /usr/local/bin
if [ -d "$BIN_DIR" ] || mkdir -p "$BIN_DIR" 2>/dev/null; then
  if echo "$WRAPPER_SCRIPT" > "$WRAPPER" 2>/dev/null; then
    chmod +x "$WRAPPER"
    REGISTERED=1
    success "$WRAPPER -> $KENXPLOIT_BIN"
  fi
fi

# Method 2: Symlink in /usr/local/bin
if [ "$REGISTERED" -eq 0 ] && [ -d "$BIN_DIR" ]; then
  if ln -sf "$KENXPLOIT_BIN" "$WRAPPER" 2>/dev/null; then
    REGISTERED=1
    success "Symlink: $WRAPPER -> $KENXPLOIT_BIN"
  fi
fi

# Method 3: Add to shell RC (fallback)
if [ "$REGISTERED" -eq 0 ]; then
  detect_shell_rc
  if [ -n "$SHELL_RC" ]; then
    if ! grep -q "kenxploit" "$SHELL_RC" 2>/dev/null; then
      {
        echo ""
        echo "# KenXploit"
        echo "export PATH=\"\$PATH:$KENXPLOIT_DIR\""
      } >> "$SHELL_RC"
      success "Added to PATH in $SHELL_RC"
      warn  "Run: source $SHELL_RC (or open new terminal)"
    else
      warn "PATH entry already exists in $SHELL_RC"
    fi
    REGISTERED=1
  fi
fi

if [ "$REGISTERED" -eq 0 ]; then
  fail "Failed to register kenxploit to PATH"
  warn "Run manually: $KENXPLOIT_BIN"
  exit 1
fi

# --- Step 5: Verify ---
info "Verifying installation..."
if command -v kenxploit &>/dev/null; then
  success "kenxploit found at: $(command -v kenxploit)"
else
  warn "Command not found in current session."
  warn "Open a new terminal or run: source ~/.bashrc / ~/.zshrc"
fi

# --- Done ---
echo ""
echo -e "${CYAN}╔══════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║       Installation Complete!                  ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════════╝${NC}"
echo ""
echo "  Run:       kenxploit --help"
echo "  Config:    $KENXPLOIT_DIR/config.json"
echo ""
echo "  Examples:"
echo "    kenxploit -t https://target.com"
echo "    kenxploit -t target.com --dry-run"
echo ""
echo "  Uninstall: sudo ./uninstall.sh"
echo ""
